#!/bin/bash

START=$(date +%s)
sysbench --test=cpu --num-threads=4 --cpu-max-prime=800 run
sysbench --test=cpu --num-threads=4 --cpu-max-prime=800 run
nc -n 192.168.137.200 4000 < ToBeSent4000.txt
nc -q 0 -l 4000 > out.txt
sysbench --test=cpu --num-threads=4 --cpu-max-prime=800 run 
sysbench --test=cpu --num-threads=4 --cpu-max-prime=800 run 
nc -n 192.168.137.200 4000 < ToBeSent4000.txt
END=$(date +%s)
DIFF=$(( $END - $START )) 
echo "It took $DIFF seconds" && exit
